version: "3.8"

services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"   # Client connections
      - "8222:8222"   # HTTP monitoring interface
    command: ["-js", "-m", "8222"]  # Enable JetStream and monitoring